import Foundation

struct PodcastTopics {
    static let allTopics = [
        "Faith",
        "Prayer",
        "Hope",
        "Love",
        "Forgiveness",
        "Gratitude",
        "Patience",
        "Kindness",
        "Peace",
        "Joy",
        "Wisdom",
        "Courage",
        "Humility",
        "Compassion",
        "Perseverance",
        "Generosity",
        "Integrity",
        "Mercy",
        "Grace",
        "Salvation",
        "Redemption",
        "Discipleship",
        "Worship",
        "Service",
        "Evangelism",
        "Stewardship",
        "Leadership",
        "Family",
        "Marriage",
        "Parenting",
        "Friendship",
        "Community",
        "Suffering",
        "Healing",
        "Temptation",
        "Spiritual Growth",
        "God's Promises",
        "God's Love",
        "God's Sovereignty",
        "Holy Spirit",
        "Jesus Christ",
        "The Cross",
        "Resurrection",
        "Heaven",
        "Eternity"
    ]
} 